user:
  password_minimum: 3
  email_regex: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i'
  name_max: 100
  email_max: 100
  avatar_default: "user/avatar.png"
book:
  min: 3
  max_page_book: 5
  max_page_search: 24
category:
  min: 5
author:
  max_page: 4
  min: 3
  image_type: ["image/jpeg", "image/gif", "image/png"]
  image_size: 5
  image_resize: [200, 200]
  image_accept: "image/jpeg, image/gif, image/png"
gender:
  female: "female"
  male: "male"
  other: "other"
max_page_category: 8
max_page_user: 8
publishers:
  max_page: 4
  min: 3
  avatar_default: "default/publisher_img_default.jpg"
  image_type: ["image/jpeg", "image/gif", "image/png"]
  image_size: 5
  image_resize: [200, 200]
  image_accept: "image/jpeg, image/gif, image/png"
status:
  success: 200
  internal_server_error: 500
  not_found: 404
max_item_book: 20
order:
  max_page: 6
  status:
    pending: 0
    approved: 1
    returned: 2
    canceled: 3
order_detail:
  status:
    pending: 0
    accept: 1
    disagree: 2
  quantity_real:
    inscrese: "inscrese"
    descrese: "descrese"
status:
  success: 200
  internal_server_error: 500
  not_found: 404
